// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzWbafc01HMwIETgNEa2_aEKtAc80-lOg',
    appId: '1:739770944620:web:04eb610b0cc659547b5c49',
    messagingSenderId: '739770944620',
    projectId: 'cartodex-f5a25',
    authDomain: 'cartodex-f5a25.firebaseapp.com',
    storageBucket: 'cartodex-f5a25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhzYtOHCMqYNrfgh0vG2PDdsrGimKyuao',
    appId: '1:739770944620:android:4972b731d9d7d0fa7b5c49',
    messagingSenderId: '739770944620',
    projectId: 'cartodex-f5a25',
    storageBucket: 'cartodex-f5a25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKvKgqax4urKBrk0Rz6eaEovE-EJxlEe8',
    appId: '1:739770944620:ios:ef01c7c689b767fe7b5c49',
    messagingSenderId: '739770944620',
    projectId: 'cartodex-f5a25',
    storageBucket: 'cartodex-f5a25.firebasestorage.app',
    iosClientId: '739770944620-ug1pafjj92kcqb8mbstctmb28liv2ge5.apps.googleusercontent.com',
    iosBundleId: 'com.example.cartodex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKvKgqax4urKBrk0Rz6eaEovE-EJxlEe8',
    appId: '1:739770944620:ios:ef01c7c689b767fe7b5c49',
    messagingSenderId: '739770944620',
    projectId: 'cartodex-f5a25',
    storageBucket: 'cartodex-f5a25.firebasestorage.app',
    iosClientId: '739770944620-ug1pafjj92kcqb8mbstctmb28liv2ge5.apps.googleusercontent.com',
    iosBundleId: 'com.example.cartodex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzWbafc01HMwIETgNEa2_aEKtAc80-lOg',
    appId: '1:739770944620:web:5e0ebef86e1683e47b5c49',
    messagingSenderId: '739770944620',
    projectId: 'cartodex-f5a25',
    authDomain: 'cartodex-f5a25.firebaseapp.com',
    storageBucket: 'cartodex-f5a25.firebasestorage.app',
  );
}
